language: cpp

cache:
  directories:
    - build_linux/gtest
    - build_linux/openssl
    - build_linux/protobuf
    - build_linux/postgresql

os:
  - linux

dist: trusty
sudo: required

before_install:
  - sudo dpkg --add-architecture i386
  - sudo apt-get update -qq
  - sudo apt-get install -y g++-4.8-multilib lib32stdc++-4.8-dev
    linux-libc-dev:i386 xutils-dev

  - export CXX=g++-4.8 CC=gcc-4.8

  # IDA SDK
  - openssl aes-256-cbc -k "$idasdk_secret" -in third_party/idasdk.zip.enc
    -out third_party/idasdk.zip -d
  - unzip -q third_party/idasdk.zip -d third_party/

script:
  - cd build_linux
  - cmake .. -DCMAKE_RULE_MESSAGES=OFF -DCMAKE_BUILD_TYPE=Release
  - make

env:
  global:
    - secure: Dz7DLm6tkwOurtQxcBLiZ/HsTfvGxJ+f8r2oJNTYX3oDKpF7cyhyx/TVgc02H2f/Y77Ja5p33dp5GK3u4iAqzm9QIB7J4nXRlzZfR4Z8zdZrSm94emWNhx6YfEk7Lzp3zw+W5W8jHuKOKoK3b3z7kXROUhGc4ZtHdAF9rj9YMOdJga8f37/2IxDJFX5oK3+uzBSg1VbFdSP3Xf5xNEwAIkkuH6a+3AyIc1qWmy5xXN7/moEabVY8Ui8xJzshvkPz6dtFwuJ0pQA63Tlj910Sd0vt8/5Cl0KmPxXIL0Tt0ss4zI8piMQuVSZfGpvjBUN7NILlFU8AOMcKeoVNWnxMMtEYwTEM4BoqVb6+9ET5qQMlMPYPs0Iydo/9+v7BKGwFFQEBSYo5kxKEYULQ7S5kFMxHosjCLDZ+cPORKGbGmFxsLeI1Ov9aGlpuJhpkALlupvOWKYMgwotf4eg9kPJz0mkIFQHSnTB/7ix4oyPNI3g8n5KhP9xl/yV2k8LH0s2js6ucISD+ZcCQLghjef6ylu3pmfqUTXd7Yn4pXviF1b/y1kg4Q7bw1LZVjzlO4sQqTAiXQ6Uifq2OVPOeOl6M2tX1DUVqj4B52+CnHn45x7opi/87+H3wlPjDfs0Aggg+fL5QOSzGx4dmVgAXtdHjnP8MKGEIy/j7myiimAMjzAs=
