image: Visual Studio 2015

environment:
  idasdk_secret:
    secure: e8rrgX8BRIaH59lHhkE56P7z9XjkkoN59li6krpEUOE=

matrix:
  fast_finish: true

cache:
  - build_msvc\openssl
  - build_msvc\postgresql
  - build_msvc\protobuf

install:
  - call "%VS140COMNTOOLS%\..\..\VC\vcvarsall.bat" x86

  - mkdir build_msvc

  # IDA SDK
  - C:\OpenSSL-Win32\bin\openssl.exe aes-256-cbc -k "%idasdk_secret%"
    -in third_party\idasdk.zip.enc -out third_party\idasdk.zip -d
  #- 7z x -bt -mmt2 idasdk.zip
  - unzip -q third_party\idasdk.zip -d third_party

before_build:
  - cd build_msvc
  - cmake .. -DCMAKE_BUILD_TYPE=Release

build_script:
  - msbuild binexport.sln /p:Configuration=Release /m
